### ISSUE TITLE
model 层的Promise对象的问题

### ISSUE THREAD

**Issue by lou920217** [ele828/easy-blog#2]
想问下您的model层里的给Schema设置静态方法的时候用的Promise对象是哪儿引入的？是express库里的，还是其他的？

**Comment by ele828** [comment]
这个应该是node带的。。。

**Comment by lou920217** [comment]
嗯，知道了，我用的是低版本的nodejs，不支持这个promise，不过已经解决，引入了这polyfill-- https://github.com/then/promise

**Comment by ele828** [comment]
@2fengzi  好的 :)
